### ISSUE TITLE
position encoding 是不是错了 wrong?

### ISSUE THREAD

**Issue by cycy1013** [olof98johansson/StockPrediction#4]
position encoding 是不是错了 wrong?
我试了一下如下代码:
import torch
position = torch.arange(99, dtype=torch.float).reshape(1, -1, 1) #[1,99,1]
dimension = torch.arange(512, dtype=torch.float).reshape(1, 1, -1)#[1,1,512]
phase = (position / 1e4) ** (dimension // 512) # [1, 99, 512]
#print(phase)

aa=torch.where(dimension.long() % 2 == 0, -torch.sin(phase), torch.cos(phase))
print(aa)
-------------------------------------------------------------
tensor([[[-0.8415,  0.5403, -0.8415,  ...,  0.5403, -0.8415,  0.5403],
         [-0.8415,  0.5403, -0.8415,  ...,  0.5403, -0.8415,  0.5403],
         [-0.8415,  0.5403, -0.8415,  ...,  0.5403, -0.8415,  0.5403],
两个值在交替，不应该这样吧？

**Comment by olof98johansson** [comment]
Resolved now! Check the current transformer.py
